### ISSUE TITLE
Impact of the SED in the PSF model performance 

### ISSUE THREAD

**Issue by tobias-liaudat** [tobias-liaudat/wf-SEDs#16]
# Project

### Main idea

Evaluate the performance of the model as a function of the number of bins used. The input 8-band SED is interpolated to get more bands. However, the model is not doing any interpolation, the PSFs are generated with the forward model which will be slow if using a high number of bins.

### Setting

We will use a WFE resolution of `256`. The input SED information will be `8` bins taken from the `13` SED templates of the Pickles library.

The model used will be: 
- `model =poly`, `d_max_nonparam=5`, `n_zernikes =15` and `d_max=2` (21 DD features)

Use the learning rates and the number of epochs from the paper.

### Ground truth dataset
`2000` training stars, `400` validation stars.
WFE resolution of `256` (the same as the model).
All datasets should be from the same `C_poly`. 
Each star will be generated using the full 350-point SED template.

Use the same star positions, star type and `C_poly` as the dataset used on the WaveDiff paper.

### Observed dataset
Same positions, WFE resolution, `C_poly`and assignment of SED template.

**Noiseless scenario**
- [x] (**A_0**) Using `8 bins` without noise.
- [x] (**B_0**) Using `16 bins` (interpolated from the 8 bins) without noise.
- [x] (_Optional_) (**C_0**) Using `32 bins` (interpolated from the 8 bins) without noise.

**Noisy scenario**
- [x] (**A_1**) Using `8 bins` with noise of `sigma=0.005`.
- [x] (**A_2**) Using` 8 bins` with noise of `sigma=0.01`.
- [x] (**A_3**) Using `8 bins` with noise of `sigma=0.02`.
- [x] (**B_1**) Using `16 bins` (interpolated from the 8 bins)  with noise of `sigma=0.005`.
- [x] (**B_2**) Using `16 bins` (interpolated from the 8 bins)  with noise of `sigma=0.01`.
- [x] (**B_3**) Using  `16 bins`(interpolated from the 8 bins)  with noise of `sigma=0.02`.
- [x] (_Optional_) (**C_1**) Using `32 bins` (interpolated from the 8 bins)  with noise of `sigma=0.005`.
- [x] (_Optional_) (**C_2**) Using `32 bins` (interpolated from the 8 bins)  with noise of `sigma=0.01`.
- [x] (_Optional_) (**C_3**) Using `32 bins` (interpolated from the 8 bins)  with noise of `sigma=0.02`.

## Tests

- [x] Run the WF-PSF model in all the datasets.
- [x] Plot the results.
- [x] Write the results in the overleaf.
- [x] Use the model trained with the noiseless 8-bins SED and apply the interpolation procedure for the inference (testing).

**Comment by CentofantiEze** [comment]
Should I leave the 350 points SEDs (which will use the 350 mono PSFs) for the testing dataset? Eventually we will use galaxy SEDs and their quality will also introduce errors. So should we test with the same number of bins as the GT so we only see the impact of the binning and noise on the optimisation procedure?

**Comment by tobias-liaudat** [comment]
The GT in the testing dataset should be generated the same way as the observations (but without the additive noise), using 350 points.

We will later evaluate with galaxy SEDs and see how the errors propagate to different SEDs.

**Comment by CentofantiEze** [comment]
Yes the PSFs are generated with 350 points. But how many SED points should we use for the model in the testing scenario. The same as the training for each case (8, 16, 32) or the same as the GT (350).

**Comment by tobias-liaudat** [comment]
Ah ok, mm the same as in the training.

**Comment by CentofantiEze** [comment]
All results were documented on Section 5 of the internship notes. Bonus: spatial and numerical error distribution.
